rootProject.name = "HyakuninReader"
include(":app")
include(":domain")
include(":infrastructure:storage")
include(":infrastructure:database")
include(":state")
include(":feature:corecomponent")
include(":feature:splash")
include(":feature:trainingmenu")
include(":feature:trainingstarter")
include(":feature:trainingresult")
include(":feature:exammenu")
include(":feature:examstarter")
include(":feature:examresult")
include(":feature:examhistory")
include(":feature:question")
include(":feature:material")
include(":feature:support")
